const fruits=new Array(5)
fruits.push("Banana")
fruits.push("grapes","Apple")
console.log(fruits)
const removedfruits=fruits.pop()
console.log(removedfruits)
fruits.unshift("Mango")
console.log(fruits)
fruits.shift("pineapple")
console.log(fruits)